name: Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis-version: [6, 7]

    env:
      APPCRONS_STAG_DSN: ${{ secrets.APPCRONS_STAG_DSN }}
      REDIS_URL: ${{ secrets.REDIS_URL }}

    steps:
      - name: Start Redis
        uses: supercharge/redis-github-action@1.7.0
        with:
          redis-version: ${{ matrix.redis-version }}
          redis-remove-container: true

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: make install

      - name: Run tests
        run: make stage # Runs tests in the staging environment

      - name: Trigger deployment
        if: success()
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/deploy-to-render.com.yml/dispatches \
          -d '{"ref": "${{ github.ref_name }}"}'
